OER/OpenStax/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root controller: :webview, action: :home

  get :dashboard, controller: :webview, action: :index

  scope module: :static_pages do
    get :about
    get :contact
    get :copyright
    get :developers
    get :help
    get :privacy
    get :share
    get :terms
  end

  apipie

  api :v1, default: true do
    resources :exercises do
      match :search, action: :index, via: [:get, :post], on: :collection

      publishable
    end

    resources :vocab_terms do
      match :search, action: :index, via: [:get, :post], on: :collection

      publishable
    end

    resources :users, only: [:index]

    resource :user, only: [:show, :update, :destroy]

    resources :books, only: [:index, :show], param: :uuid
  end

  mount OpenStax::Accounts::Engine => :accounts
  mount FinePrint::Engine => :fine_print
  mount ActiveStorage::Engine, at: '/rails/active_storage'
  mount OpenStax::Utilities::Engine => :status

  use_doorkeeper do
    controllers applications: :'oauth/applications'
  end

  namespace :admin do
    get :/, controller: :console, action: :index

    resources :administrators, only: [:index, :create, :destroy]

    resources :exceptions, only: [:show]

    resources :licenses

    resources :users, only: [:index] do
      member do
        put :become
        patch :delete
        patch :undelete
      end
    end

    resources :delegations, except: :show do
      get :users, on: :collection
    end

    resources :publications, only: :index do
      collection do
        patch :update
        get :collaborators
      end
    end

    resources :exercises, only: [] do
      get :invalid, on: :collection
    end
  end

  namespace :dev do
    resources :users, only: [:create] do
      post :generate, on: :collection
    end
  end

  # Catch-all frontend route, excluding active_storage
  # https://github.com/rails/rails/issues/31228
  get :'*path', controller: :webview, action: :index, constraints: ->(req) do
    req.path.exclude? 'rails/active_storage'
  end
end

OER/OpenStax/app/controllers/admin/console_controller.rb
module Admin
  class ConsoleController < BaseController
    respond_to :js

    def index
    end
  end
end

OER/OpenStax/app/views/admin/console/_exceptions.html.erb
<h5>Raise Exception</h5>
<ul class="normal">
  <li><%= link_to 'SecurityTransgression',
                  admin_exception_url('SecurityTransgression') %></li>
  <li><%= link_to 'ActiveRecord::RecordNotFound',
                  admin_exception_url('ActiveRecord::RecordNotFound') %></li>
  <li><%= link_to 'ActionController::RoutingError',
                  admin_exception_url('ActionController::RoutingError',
                                       args: '/blah/blah/blah'.inspect) %></li>
  <li><%= link_to 'AbstractController::ActionNotFound',
                  admin_exception_url('AbstractController::ActionNotFound') %></li>
  <li><%= link_to 'ActionView::MissingTemplate',
                  admin_exception_url('ActionView::MissingTemplate',
                                       args: [['a', 'b'], 'path',
                                              ['pre1', 'pre2'],
                                              'partial', 'details'].inspect) %></li>
  <li><%= link_to 'NotYetImplemented',
                  admin_exception_url('NotYetImplemented') %></li>
  <li><%= link_to 'IllegalArgument',
                  admin_exception_url('IllegalArgument') %></li>
</ul>

OER/OpenStax/app/views/admin/console/_index.html.erb
<%= osu.block_to_partial 'shared/modal',
                         html_id: 'admin_console_dialog',
                         width: '900px',
                         height: '500px' do %>

  <div class="modal-header" style="border-bottom: none">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <ul class="nav nav-tabs tight-bottom">
      <li class="active"><a href="#manage-tab" data-toggle="tab">Manage</a></li>
      <li><a href="#exceptions-tab" data-toggle="tab">Exceptions</a></li>
      <% unless Rails.env.production? %>
        <li class="dev">
          <a href="#dev-tab" data-toggle="tab" class="orange">Dev</a>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="modal-body">

    <div id="dialog-local-alerts"></div>

    <div class="tab-content">
      <div class="tab-pane active" id="manage-tab">
        <%= render partial: 'admin/console/manage' %>
      </div>

      <div class="tab-pane" id="exceptions-tab">
        <%= render partial: 'admin/console/exceptions' %>
      </div>

      <% unless Rails.env.production? %>
        <div class="tab-pane" id="dev-tab">
          <%= render partial: 'dev/console/index' %>
        </div>
      <% end %>
    </div>

  </div>

<% end %>

OER/OpenStax/app/views/admin/console/_manage.html.erb
<h5>Manage</h5>
<ul class="normal">
  <li><%= link_to "Users", admin_users_url %></li>
  <li><%= link_to "Administrators", admin_administrators_url %></li>

  <br><br>

  <li><%= link_to "Applications", oauth_applications_url %></li>

  <br><br>

  <li><%= link_to "Delegations", admin_delegations_url %></li>

  <br><br>

  <li><%= link_to "Publications", admin_publications_url %></li>

  <br><br>

  <li><%= link_to "Site Terms", fine_print.root_url %></li>
  <li><%= link_to "Content Licenses", admin_licenses_url %></li>

  <li><%= link_to "Invalid Exercises", invalid_admin_exercises_url %></li>
</ul>

OER/OpenStax/app/views/admin/console/index.js.erb
Exercises.Ui.renderAndOpenDialog(
  'admin_console_dialog', '<%= j(render partial: "admin/console/index") %>'
);