OER/OpenStax/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root controller: :webview, action: :home

  get :dashboard, controller: :webview, action: :index

  scope module: :static_pages do
    get :about
    get :contact
    get :copyright
    get :developers
    get :help
    get :privacy
    get :share
    get :terms
  end

  apipie

  api :v1, default: true do
    resources :exercises do
      match :search, action: :index, via: [:get, :post], on: :collection

      publishable
    end

    resources :vocab_terms do
      match :search, action: :index, via: [:get, :post], on: :collection

      publishable
    end

    resources :users, only: [:index]

    resource :user, only: [:show, :update, :destroy]

    resources :books, only: [:index, :show], param: :uuid
  end

  mount OpenStax::Accounts::Engine => :accounts
  mount FinePrint::Engine => :fine_print
  mount ActiveStorage::Engine, at: '/rails/active_storage'
  mount OpenStax::Utilities::Engine => :status

  use_doorkeeper do
    controllers applications: :'oauth/applications'
  end

  namespace :admin do
    get :/, controller: :console, action: :index

    resources :administrators, only: [:index, :create, :destroy]

    resources :exceptions, only: [:show]

    resources :licenses

    resources :users, only: [:index] do
      member do
        put :become
        patch :delete
        patch :undelete
      end
    end

    resources :delegations, except: :show do
      get :users, on: :collection
    end

    resources :publications, only: :index do
      collection do
        patch :update
        get :collaborators
      end
    end

    resources :exercises, only: [] do
      get :invalid, on: :collection
    end
  end

  namespace :dev do
    resources :users, only: [:create] do
      post :generate, on: :collection
    end
  end

  # Catch-all frontend route, excluding active_storage
  # https://github.com/rails/rails/issues/31228
  get :'*path', controller: :webview, action: :index, constraints: ->(req) do
    req.path.exclude? 'rails/active_storage'
  end
end

OER/OpenStax/app/models/user.rb
class User < ApplicationRecord

  USERNAME_FORBIDDEN_CHAR_REGEX = /[^\w-]/

  acts_as_voter

  belongs_to :account, class_name: 'OpenStax::Accounts::Account', autosave: true

  has_many :groups_as_member, through: :account
  has_many :groups_as_owner, through: :account

  has_one :administrator

  has_many :authors
  has_many :copyright_holders

  has_many :delegations_as_delegator, class_name: 'Delegation',
                                      foreign_key: :delegator_id,
                                      inverse_of: :delegator
  has_many :delegations_as_delegate, class_name: 'Delegation', as: :delegate

  has_many :sortings

  has_many :applications, as: :owner, class_name: 'Doorkeeper::Application'

  validates :account, uniqueness: true

  delegate :username, :first_name, :last_name, :full_name, :title,
           :name, :casual_name, :first_name=, :last_name=, :full_name=,
           :title=, :faculty_status, :role, :uuid, :support_identifier, to: :account

  def self.anonymous
    AnonymousUser.instance
  end

  def default_authors
    [ self ] + delegations_as_delegate.to_a.select(&:can_assign_authorship).map(&:delegator)
  end

  def default_copyright_holders
    [ self ] + delegations_as_delegate.to_a.select(&:can_assign_copyright).map(&:delegator)
  end

  def is_human?
    true
  end

  def is_application?
    false
  end

  def is_anonymous?
    false
  end

  def is_administrator?
    !administrator.nil?
  end

  def is_deleted?
    !deleted_at.nil?
  end

  def destroy
    update_attribute(:deleted_at, Time.now)
  end

  def delete
    update_column(:deleted_at, Time.now)
  end

  def undelete
    update_column(:deleted_at, nil)
  end

end

OER/OpenStax/app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    before_action :set_user, only: [:show, :edit, :update, :become, :delete, :undelete]

  # GET /users
    def index
      handle_with Admin::UsersSearch
    end

    # PUT /users/1/become
    def become
      sign_in @user
      redirect_to root_url, notice: "Logged in as #{@user.name}"
    end

    # PATCH /users/1/delete
    def delete
      @user.delete
      respond_to do |format|
        format.html do
          redirect_to admin_users_url, notice: "#{@user.name}'s account has been disabled."
        end
        format.js { render 'admin/users/delete' }
      end
    end

    # PATCH /users/1/undelete
    def undelete
      @user.undelete
      respond_to do |format|
        format.html do
          redirect_to admin_users_url, notice: "#{@user.name}'s account has been enabled."
        end
        format.js { render 'admin/users/delete' }
      end
    end

    protected

    def set_user
      @user = User.find(params[:id])
    end
  end
end

OER/OpenStax/app/controllers/api/v1/users_controller.rb
module Api::V1
  class UsersController < OpenStax::Api::V1::ApiController

    resource_description do
      api_versions "v1"
      short_description 'A human user of OpenStax Exercises.'
      description <<-EOS
        Users have the following String attributes:
        username
        first_name
        last_name
        full_name
        title
      EOS
    end

    #########
    # index #
    #########

    MAX_USERS = 20

    api :GET, '/users', 'Return a set of Users matching query terms'
    description <<-EOS
      Accepts a query string along with options and returns a JSON
      representation of the matching Users. Some User data may be
      filtered out depending on the caller's status and privileges in
      the system. The schema for the returned JSON result is shown below.

      #{json_schema(OpenStax::Accounts::Api::V1::AccountSearchRepresenter, include: :readable)}
    EOS
    # Using route helpers doesn't work in test or production, probably has to do with initialization order
    example "#{api_example(url_base: 'https://users.openstax.org/api/users',
                           url_end: '?q=username:bob%20name=Jones')}"
    param :q, String, required: true, desc: <<-EOS
      The search query string, built up as a space-separated collection of
      search conditions on different fields. Each condition is formatted as
      "field_name:comma-separated-values". The resulting list of users will
      match all of the conditions (boolean 'and'). Each condition will produce
      a list of users where those users must match any of the
      comma-separated-values (boolean 'or'). The fields_names and their
      characteristics are given below.
      When a field is listed as using wildcard matching, it means that any
      fields that start with a comma-separated-value will be matched.

      * `username` &ndash; Matches usernames, case insensitive. (uses wildcard matching)
      * `first_name` &ndash; Matches users' first names, case insensitive. (uses wildcard matching)
      * `last_name` &ndash; Matches users' last names, case insensitive. (uses wildcard matching)
      * `name` &ndash; Matches users' first, last, or full names, case insenstive. (uses wildcard matching)
      * `id` &ndash; Matches users' IDs exactly.
      * `email` &ndash; Matches users' emails exactly.

      You can also add search terms without prefixes, separated by spaces.
      These terms will be searched for in all of the prefix categories.
      Any matching users will be returned. When combined with prefixed search
      terms, the final results will contain users matching any of the non
      prefixed terms and all of the prefixed terms.

      Examples:

      `username:ric` &ndash; returns 'richb' and 'ricardo' users.

      `username:ric name:"Van Buren"` &ndash; returns the 'Ricardo Van Buren' user.

      `ric` &ndash; returns 'richb', 'ricardo', and 'Jimmy Rich' users.
    EOS
    param :order_by, String, desc: <<-EOS
      A string that indicates how to sort the results of the query. The string
      is a comma-separated list of fields with an optional sort direction. The
      sort will be performed in the order the fields are given.
      The fields can be one of #{
        OpenStax::Accounts::SearchLocalAccounts::SORTABLE_FIELDS.keys.map {|sf| "`"+sf+"`"}
                                                                     .join(', ')
      }.
      Sort directions can either be `ASC` for
      an ascending sort, or `DESC` for a
      descending sort. If not provided, an ascending sort is assumed. Sort
      directions should be separated from the fields by a space.
      (default: `username ASC`)

      Example:

      `last_name, username DESC` &ndash; sorts by last name ascending, then by username descending
    EOS
    def index
      OSU::AccessPolicy.require_action_allowed! :search, current_api_user, User
      outputs = OpenStax::Accounts::SearchAccounts.call(params[:q], params.slice(:order_by)).outputs

      outputs[:items] = outputs[:items].none if outputs[:total_count] > MAX_USERS

      respond_with outputs, represent_with: OpenStax::Accounts::Api::V1::AccountSearchRepresenter
    end

    ########
    # show #
    ########

    api :GET, '/user', "Gets the current user's profile"
    description <<-EOS
      Gets the current user's profile.

      #{json_schema(Api::V1::UserRepresenter, include: :readable)}
    EOS
    def show
      standard_read(current_human_user)
    end

    ##########
    # update #
    ##########

    api :PATCH, '/user', "Updates the current user's profile"
    description <<-EOS
      Updates the current user's profile.

      #{json_schema(Api::V1::UserRepresenter, include: :writeable)}
    EOS
    def update
      standard_update(current_human_user)
    end

    ###########
    # destroy #
    ###########

    api :DELETE, '/user', "Disables the current user's account"
    description <<-EOS
      Disables the current user's account.
    EOS
    def destroy
      standard_destroy(current_human_user)
    end

  end
end

OER/OpenStax/app/controllers/dev/base_controller.rb
# Copyright 2011-2012 Rice University. Licensed under the Affero General Public 
# License version 3 or later.  See the COPYRIGHT file for details.

module Dev
  class BaseController < ApplicationController

    before_action :development_or_test!

    skip_before_action :authenticate_user!
    fine_print_skip :general_terms_of_use, :privacy_policy

    protected

    def development_or_test!
      return if Rails.env.development? || Rails.env.test?
      raise SecurityTransgression
    end

  end
end

OER/OpenStax/app/controllers/dev/users_controller.rb
module Dev
  class UsersController < BaseController

    def create
      handle_with(Dev::UsersCreate)
    end

    def generate
      handle_with(Dev::UsersGenerate)
    end

  end
end

OER/OpenStax/app/views/dev/users/_index.html.erb
<h5>Create User</h5>
<div style="width: 500px">
  <%= lev_form_for :create, url: dev_users_url, remote: true,
                   html: {id: 'create-user-form', class: 'form-horizontal'} do |f| %>
    <div class='form-group'>
      <label class='col-sm-3 control-label'>Username</label>
      <div class='col-sm-9'>
        <%= f.text_field :username, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='col-sm-3 control-label'>First name</label>
      <div class='col-sm-9'>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='col-sm-3 control-label'>Last name</label>
      <div class='col-sm-9'>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='col-sm-3 control-label'>Full name</label>
      <div class='col-sm-9'>
        <%= f.text_field :full_name, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
      <label class='col-sm-3 control-label'>Title</label>
      <div class='col-sm-9'>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>
    <div class='form-group'>
        <label class='col-sm-3 control-label'>Administrator?</label>
        <div class=' col-sm-9'>
          <%= f.check_box :is_administrator %>
        </div>
    </div>
    <div class='form-group'>
        <label class='col-sm-3 control-label'>Agreed to Terms?</label>
        <div class=' col-sm-9'>
          <%= f.check_box :agreed_to_terms %>
        </div>
    </div>
    <div class='form-group'>
      <div class='col-sm-offset-3 col-sm-9'>
        <%= f.submit 'Create User', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

<h5>Auto-generate Users</h5>
<%= lev_form_for :generate, url: generate_dev_users_url, remote: true,
                 html: {id: 'generate-users-form', class: 'form-inline'} do |f| %>

  <div>Generate <%= f.text_field :count, style: 'width:50px' %> user(s)</div>
  <div><%= f.submit 'Do It', class: 'btn btn-primary' %></div>
<% end %>

OER/OpenStax/app/views/dev/users/create.js.erb
<%= unless_errors alerts_html_id: 'dialog-local-alerts' do %>
  <% add_local_success_alert  now: true, content: "Created user '#{@handler_result.outputs.user.name}'." %>
  <%= js_refresh_alerts alerts_html_id: 'dialog-local-alerts' %>

  $('#create-user-form')[0].reset();
<% end %>

OER/OpenStax/app/views/dev/users/generate.js.erb
<%= unless_errors alerts_html_id: 'dialog-local-alerts' do %>
  <% add_local_success_alert  now: true, content: "Created #{@handler_result.outputs[:count]} user(s)." %>
  <%= js_refresh_alerts alerts_html_id: 'dialog-local-alerts' %>
  $('#generate-users-form')[0].reset();
<% end %>